"""PostgreSQL storage backend for sprintctl remote mode.

All public functions mirror sprintctl.db, but accept a PgStore instead of a
sqlite3.Connection. The PgStore wraps a psycopg connection and carries repo_id,
which is prepended to every query as a tenant discriminator.

Timestamps are stored as timestamptz in pg and returned as Python datetime
objects by psycopg. Every function normalises rows before returning so callers
receive the same ISO-8601 string timestamps they get from the sqlite backend.

Event payloads are stored as jsonb. psycopg deserialises them to dicts on read,
so no json.loads() is needed here. The same contracts.canonicalize_event_payload
path is used for writes.
"""

from __future__ import annotations

import json
import secrets
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

try:
    import psycopg
    from psycopg.rows import dict_row
    from psycopg.errors import UniqueViolation
    _PSYCOPG_AVAILABLE = True
except ImportError:  # pragma: no cover
    _PSYCOPG_AVAILABLE = False

from . import contracts as _contracts
from .db import (
    VALID_TRANSITIONS,
    SPRINT_TRANSITIONS,
    SPRINT_KINDS,
    CLAIM_TYPES,
    REF_TYPES,
    KNOWLEDGE_EVENT_TYPES,
    TAKEUP_EVENT_TYPES,
    InvalidTransition,
    ClaimConflict,
    CLAIM_IDENTITY_STATUS_PROVEN,
    CLAIM_IDENTITY_STATUS_LEGACY,
    MAX_CLAIM_TOKEN_INSERT_RETRIES,
    _validate_ref_url,
    _claim_identity_status,
    _claim_event_identity,
    _claim_attempt_identity,
    _takeup_key,
    _takeup_actor_key,
    _decode_event_payload,
    process_takeup_events,
)

# ---------------------------------------------------------------------------
# DDL — single schema version, created idempotently
# ---------------------------------------------------------------------------

_DDL = """
CREATE TABLE IF NOT EXISTS schema_version (
    version integer NOT NULL
);

INSERT INTO schema_version(version)
SELECT 1
WHERE NOT EXISTS (SELECT 1 FROM schema_version);

CREATE TABLE IF NOT EXISTS sprint (
    repo_id    text        NOT NULL,
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL,
    goal       text        NOT NULL DEFAULT '',
    start_date date,
    end_date   date,
    status     text        NOT NULL DEFAULT 'planned'
                           CHECK (status IN ('active', 'closed', 'planned')),
    created_at timestamptz NOT NULL DEFAULT now(),
    kind       text        NOT NULL DEFAULT 'active_sprint'
                           CHECK (kind IN ('active_sprint', 'backlog', 'archive')),
    UNIQUE (repo_id, id)
);

CREATE TABLE IF NOT EXISTS track (
    repo_id     text        NOT NULL,
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sprint_id   bigint      NOT NULL,
    name        text        NOT NULL,
    description text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (repo_id, id),
    UNIQUE (repo_id, sprint_id, name),
    FOREIGN KEY (repo_id, sprint_id)
        REFERENCES sprint(repo_id, id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_item (
    repo_id     text        NOT NULL,
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id    bigint      NOT NULL,
    sprint_id   bigint      NOT NULL,
    title       text        NOT NULL,
    description text        NOT NULL DEFAULT '',
    status      text        NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'active', 'done', 'blocked')),
    assignee    text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (repo_id, id),
    FOREIGN KEY (repo_id, sprint_id)
        REFERENCES sprint(repo_id, id)
        ON DELETE CASCADE,
    FOREIGN KEY (repo_id, track_id)
        REFERENCES track(repo_id, id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event (
    repo_id      text        NOT NULL,
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sprint_id    bigint      NOT NULL,
    work_item_id bigint,
    source_type  text        NOT NULL
                             CHECK (source_type IN ('actor', 'daemon', 'system')),
    actor        text        NOT NULL,
    event_type   text        NOT NULL,
    payload      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (repo_id, id),
    FOREIGN KEY (repo_id, sprint_id)
        REFERENCES sprint(repo_id, id)
        ON DELETE CASCADE,
    FOREIGN KEY (repo_id, work_item_id)
        REFERENCES work_item(repo_id, id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS claim (
    repo_id            text        NOT NULL,
    id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_id       bigint      NOT NULL,
    agent              text        NOT NULL,
    claim_type         text        NOT NULL DEFAULT 'execute'
                                      CHECK (claim_type IN ('inspect', 'execute', 'review', 'coordinate')),
    exclusive          boolean     NOT NULL DEFAULT true,
    created_at         timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NOT NULL,
    heartbeat          timestamptz NOT NULL DEFAULT now(),
    branch             text,
    worktree_path      text,
    commit_sha         text,
    pr_ref             text,
    claim_token        text,
    runtime_session_id text,
    instance_id        text,
    hostname           text,
    pid                integer,
    UNIQUE (repo_id, id),
    FOREIGN KEY (repo_id, work_item_id)
        REFERENCES work_item(repo_id, id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ref (
    repo_id      text        NOT NULL,
    id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_id bigint      NOT NULL,
    ref_type     text        NOT NULL DEFAULT 'other'
                              CHECK (ref_type IN ('pr', 'issue', 'doc', 'other')),
    url          text        NOT NULL,
    label        text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (repo_id, id),
    FOREIGN KEY (repo_id, work_item_id)
        REFERENCES work_item(repo_id, id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dep (
    repo_id         text        NOT NULL,
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         bigint      NOT NULL,
    blocked_item_id bigint      NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (repo_id, id),
    UNIQUE (repo_id, item_id, blocked_item_id),
    FOREIGN KEY (repo_id, item_id)
        REFERENCES work_item(repo_id, id)
        ON DELETE CASCADE,
    FOREIGN KEY (repo_id, blocked_item_id)
        REFERENCES work_item(repo_id, id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_claim_token
    ON claim(repo_id, claim_token)
    WHERE claim_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sprint_repo_archived
    ON sprint(repo_id, status, kind, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_event_repo_sprint_type_ts
    ON event(repo_id, sprint_id, event_type, created_at);

CREATE INDEX IF NOT EXISTS idx_work_item_repo_sprint_status
    ON work_item(repo_id, sprint_id, status);

CREATE INDEX IF NOT EXISTS idx_track_repo_sprint
    ON track(repo_id, sprint_id);

CREATE INDEX IF NOT EXISTS idx_claim_repo_item_expires
    ON claim(repo_id, work_item_id, expires_at);
"""

# The DDL text is importable for unit-level schema validation tests.
PG_DDL = _DDL


@dataclass
class PgStore:
    conn: Any  # psycopg.Connection when psycopg is available
    repo_id: str


# ---------------------------------------------------------------------------
# Connection helpers
# ---------------------------------------------------------------------------

def get_connection(url: str) -> PgStore:
    if not _PSYCOPG_AVAILABLE:  # pragma: no cover
        raise RuntimeError("psycopg is not installed. Install sprintctl[remote].")
    repo_id = _repo_id_from_cwd()
    conn = psycopg.connect(url, row_factory=dict_row)
    return PgStore(conn=conn, repo_id=repo_id)


def _repo_id_from_cwd() -> str:
    from pathlib import Path
    from . import backend as _backend
    _, repo_id, _ = _backend.resolve_repo_identity(Path.cwd())
    return repo_id or "unknown"


def init_db(store: PgStore) -> None:
    with store.conn.cursor() as cur:
        cur.execute(_DDL)
    store.conn.commit()


# ---------------------------------------------------------------------------
# Row normalisation
# ---------------------------------------------------------------------------

def _iso(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.strftime("%Y-%m-%dT%H:%M:%SZ")
    return str(value)


def _norm(row: dict) -> dict:
    """Normalise a pg row: datetimes → ISO strings, date → ISO string."""
    import datetime as _dt
    out: dict = {}
    for k, v in row.items():
        if isinstance(v, datetime):
            out[k] = _iso(v)
        elif isinstance(v, _dt.date):
            out[k] = v.isoformat()
        else:
            out[k] = v
    return out


# ---------------------------------------------------------------------------
# Sprint
# ---------------------------------------------------------------------------

def create_sprint(
    store: PgStore,
    name: str,
    goal: str = "",
    start_date: str | None = None,
    end_date: str | None = None,
    status: str = "planned",
    kind: str = "active_sprint",
) -> int:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO sprint (repo_id, name, goal, start_date, end_date, status, kind)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (store.repo_id, name, goal, start_date or None, end_date or None, status, kind),
        )
        row = cur.fetchone()
    store.conn.commit()
    return row["id"]


def get_sprint(store: PgStore, sprint_id: int) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM sprint WHERE repo_id = %s AND id = %s",
            (store.repo_id, sprint_id),
        )
        row = cur.fetchone()
    return _norm(row) if row else None


def get_active_sprint(store: PgStore) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            SELECT * FROM sprint
            WHERE repo_id = %s AND status = 'active' AND kind = 'active_sprint'
            ORDER BY created_at DESC, id DESC
            LIMIT 1
            """,
            (store.repo_id,),
        )
        row = cur.fetchone()
    return _norm(row) if row else None


def list_active_sprints(store: PgStore) -> list[dict]:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            SELECT * FROM sprint
            WHERE repo_id = %s AND status = 'active' AND kind = 'active_sprint'
            ORDER BY created_at DESC, id DESC
            """,
            (store.repo_id,),
        )
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def set_sprint_kind(store: PgStore, sprint_id: int, kind: str) -> None:
    if kind not in SPRINT_KINDS:
        raise ValueError(f"Invalid kind '{kind}'. Must be one of: {', '.join(SPRINT_KINDS)}")
    sprint = get_sprint(store, sprint_id)
    if sprint is None:
        raise ValueError(f"Sprint #{sprint_id} not found")
    with store.conn.cursor() as cur:
        cur.execute(
            "UPDATE sprint SET kind = %s WHERE repo_id = %s AND id = %s",
            (kind, store.repo_id, sprint_id),
        )
    store.conn.commit()


def list_sprints(store: PgStore) -> list[dict]:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM sprint WHERE repo_id = %s ORDER BY created_at DESC",
            (store.repo_id,),
        )
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def set_sprint_status(store: PgStore, sprint_id: int, new_status: str) -> None:
    sprint = get_sprint(store, sprint_id)
    if sprint is None:
        raise ValueError(f"Sprint #{sprint_id} not found")
    current = sprint["status"]
    if new_status not in SPRINT_TRANSITIONS[current]:
        allowed = sorted(SPRINT_TRANSITIONS[current]) or "none (terminal)"
        raise InvalidTransition(
            f"cannot transition sprint {current} -> {new_status}. Allowed: {allowed}"
        )
    with store.conn.cursor() as cur:
        cur.execute(
            "UPDATE sprint SET status = %s WHERE repo_id = %s AND id = %s",
            (new_status, store.repo_id, sprint_id),
        )
    store.conn.commit()


# ---------------------------------------------------------------------------
# Track
# ---------------------------------------------------------------------------

def get_or_create_track(
    store: PgStore,
    sprint_id: int,
    name: str,
    description: str = "",
) -> int:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO track (repo_id, sprint_id, name, description)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (repo_id, sprint_id, name) DO NOTHING
            """,
            (store.repo_id, sprint_id, name, description),
        )
        cur.execute(
            "SELECT id FROM track WHERE repo_id = %s AND sprint_id = %s AND name = %s",
            (store.repo_id, sprint_id, name),
        )
        row = cur.fetchone()
    store.conn.commit()
    return row["id"]


def list_tracks(store: PgStore, sprint_id: int) -> list[dict]:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM track WHERE repo_id = %s AND sprint_id = %s ORDER BY created_at ASC",
            (store.repo_id, sprint_id),
        )
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def get_track(store: PgStore, track_id: int) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM track WHERE repo_id = %s AND id = %s",
            (store.repo_id, track_id),
        )
        row = cur.fetchone()
    return _norm(row) if row else None


# ---------------------------------------------------------------------------
# WorkItem
# ---------------------------------------------------------------------------

def create_work_item(
    store: PgStore,
    sprint_id: int,
    track_id: int,
    title: str,
    description: str = "",
    assignee: str | None = None,
) -> int:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO work_item (repo_id, sprint_id, track_id, title, description, assignee)
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (store.repo_id, sprint_id, track_id, title, description, assignee),
        )
        row = cur.fetchone()
    store.conn.commit()
    return row["id"]


def get_work_item(store: PgStore, item_id: int) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM work_item WHERE repo_id = %s AND id = %s",
            (store.repo_id, item_id),
        )
        row = cur.fetchone()
    return _norm(row) if row else None


def list_work_items(
    store: PgStore,
    sprint_id: int | None = None,
    track_name: str | None = None,
    status: str | None = None,
) -> list[dict]:
    query = """
        SELECT wi.*, t.name AS track_name
        FROM work_item wi
        JOIN track t ON wi.repo_id = t.repo_id AND wi.track_id = t.id
        WHERE wi.repo_id = %s
    """
    params: list = [store.repo_id]
    if sprint_id is not None:
        query += " AND wi.sprint_id = %s"
        params.append(sprint_id)
    if track_name is not None:
        query += " AND t.name = %s"
        params.append(track_name)
    if status is not None:
        query += " AND wi.status = %s"
        params.append(status)
    query += " ORDER BY wi.created_at ASC"
    with store.conn.cursor() as cur:
        cur.execute(query, params)
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def set_work_item_status(
    store: PgStore,
    item_id: int,
    new_status: str,
    actor: str | None = None,
    claim_id: int | None = None,
    claim_token: str | None = None,
) -> None:
    from .db import _require_claim_proof
    item = get_work_item(store, item_id)
    if item is None:
        raise ValueError(f"Item #{item_id} not found")
    current = item["status"]
    if new_status not in VALID_TRANSITIONS[current]:
        allowed = sorted(VALID_TRANSITIONS[current]) or "none (terminal)"
        raise InvalidTransition(
            f"cannot transition {current} -> {new_status}. Allowed: {allowed}"
        )
    active_claim = _get_active_exclusive_claim_row(store, item_id)
    if active_claim is not None:
        if claim_id is None or claim_token is None:
            _emit_claim_event(
                store, active_claim,
                event_type="coordination-failure",
                actor=actor or "system",
                payload={
                    "summary": f"Item transition rejected for item #{item_id}",
                    "detail": "An exclusive claim blocked the transition because no valid claim proof was supplied.",
                    "tags": ["claims", "coordination", "ownership-proof"],
                    "operation": "item-status",
                    "reason": "missing-claim-proof",
                    "required_claim": _claim_event_identity(active_claim),
                    "attempted_by": _claim_attempt_identity(actor=actor),
                },
            )
            raise ClaimConflict(
                f"Item #{item_id} is exclusively claimed by '{active_claim['agent']}' "
                f"(claim #{active_claim['id']}). Provide --claim-id and --claim-token."
            )
        if claim_id != active_claim["id"]:
            _emit_claim_event(
                store, active_claim,
                event_type="coordination-failure",
                actor=actor or "system",
                payload={
                    "summary": f"Item transition rejected for item #{item_id}",
                    "detail": "A transition supplied a claim proof for the wrong claim id.",
                    "tags": ["claims", "coordination", "ownership-proof"],
                    "operation": "item-status",
                    "reason": "wrong-claim-id",
                    "required_claim": _claim_event_identity(active_claim),
                    "attempted_by": _claim_attempt_identity(
                        actor=actor, claim_id=claim_id, claim_token_present=claim_token is not None,
                    ),
                },
            )
            raise ClaimConflict(
                f"Item #{item_id} is exclusively claimed by '{active_claim['agent']}' "
                f"(claim #{active_claim['id']})."
            )
        _require_claim_proof(active_claim, claim_token)
    if new_status == "active":
        unresolved = [
            b for b in list_deps_blocking(store, item_id) if b["blocker_status"] != "done"
        ]
        if unresolved:
            raise InvalidTransition(
                f"cannot transition {current} -> active while blockers remain unresolved: "
                f"{[b['item_id'] for b in unresolved]}"
            )
    with store.conn.cursor() as cur:
        cur.execute(
            "UPDATE work_item SET status = %s, updated_at = now() WHERE repo_id = %s AND id = %s",
            (new_status, store.repo_id, item_id),
        )
    store.conn.commit()


def force_item_done_for_carryover(store: PgStore, item_id: int) -> None:
    """Set item status to 'done' bypassing the state machine. Carryover use only."""
    with store.conn.cursor() as cur:
        cur.execute(
            "UPDATE work_item SET status = 'done', updated_at = now() WHERE repo_id = %s AND id = %s",
            (store.repo_id, item_id),
        )


# ---------------------------------------------------------------------------
# Event
# ---------------------------------------------------------------------------

def create_event(
    store: PgStore,
    sprint_id: int,
    actor: str,
    event_type: str,
    source_type: str = "actor",
    work_item_id: int | None = None,
    payload: dict | None = None,
) -> int:
    canonical_payload = _contracts.canonicalize_event_payload(event_type, payload)
    with store.conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO event (repo_id, sprint_id, work_item_id, source_type, actor, event_type, payload)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (store.repo_id, sprint_id, work_item_id, source_type, actor, event_type,
             json.dumps(canonical_payload)),
        )
        row = cur.fetchone()
    store.conn.commit()
    return row["id"]


def _events_query(store: PgStore, sprint_id: int, *, order: str = "ASC", limit: int | None = None) -> list[dict]:
    query = """
        SELECT * FROM event
        WHERE repo_id = %s AND sprint_id = %s
        ORDER BY created_at {order}
    """.format(order=order)
    params: list = [store.repo_id, sprint_id]
    if limit is not None:
        query += " LIMIT %s"
        params.append(limit)
    with store.conn.cursor() as cur:
        cur.execute(query, params)
        rows = cur.fetchall()
    return [_norm_event(r) for r in rows]


def _norm_event(row: dict) -> dict:
    out = _norm(row)
    # pg jsonb → dict already; normalise to match sqlite string convention for
    # callers that do json.loads(event["payload"])
    payload = out.get("payload")
    if isinstance(payload, dict):
        out["payload"] = json.dumps(payload)
    return out


def list_events(store: PgStore, sprint_id: int) -> list[dict]:
    return _events_query(store, sprint_id, order="ASC")


def list_events_limited(store: PgStore, sprint_id: int, limit: int = 50) -> list[dict]:
    rows = _events_query(store, sprint_id, order="DESC", limit=limit)
    return list(reversed(rows))


def list_knowledge_candidates(store: PgStore, sprint_id: int) -> list[dict]:
    placeholders = ", ".join(["%s"] * len(KNOWLEDGE_EVENT_TYPES))
    with store.conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT * FROM event
            WHERE repo_id = %s AND sprint_id = %s AND event_type IN ({placeholders})
            ORDER BY created_at ASC, id ASC
            """,
            [store.repo_id, sprint_id, *KNOWLEDGE_EVENT_TYPES],
        )
        rows = cur.fetchall()
    result = []
    for r in rows:
        row = _norm(r)
        payload = row.get("payload")
        row["payload"] = json.loads(payload) if isinstance(payload, str) else (payload or {})
        result.append(row)
    return result


# ---------------------------------------------------------------------------
# Takeup
# ---------------------------------------------------------------------------

def _takeup_events_pg(store: PgStore, sprint_id: int | None = None) -> list[dict]:
    placeholders = ", ".join(["%s"] * len(TAKEUP_EVENT_TYPES))
    params: list = [store.repo_id, *TAKEUP_EVENT_TYPES]
    query = f"""
        SELECT * FROM event
        WHERE repo_id = %s AND event_type IN ({placeholders})
    """
    if sprint_id is not None:
        query += " AND sprint_id = %s"
        params.append(sprint_id)
    query += " ORDER BY sprint_id ASC, created_at ASC, id ASC"
    with store.conn.cursor() as cur:
        cur.execute(query, params)
        rows = cur.fetchall()
    result = []
    for r in rows:
        row = _norm(r)
        payload = row.get("payload")
        if isinstance(payload, str):
            row["payload"] = json.loads(payload)
        result.append(row)
    return result


def list_takeup_history(store: PgStore, sprint_id: int | None = None) -> dict[str, list[dict]]:
    return process_takeup_events(_takeup_events_pg(store, sprint_id))


def list_active_takeups(store: PgStore, sprint_id: int | None = None) -> list[dict]:
    return list_takeup_history(store, sprint_id)["active_takeups"]


# ---------------------------------------------------------------------------
# Claim helpers
# ---------------------------------------------------------------------------

def _serialize_claim(row: dict, *, include_secret: bool = False) -> dict:
    claim_token = row.get("claim_token")
    identity_status = _claim_identity_status(row)
    raw = dict(row)
    if not include_secret:
        raw.pop("claim_token", None)
    claim = {
        **raw,
        "claim_id": raw["id"],
        "actor": raw["agent"],
        "claim_token_present": bool(claim_token),
        "claim_token_redacted": bool(claim_token) and not include_secret,
        "identity_status": identity_status,
        "identity": {
            "claim_id": raw["id"],
            "actor": raw["agent"],
            "runtime_session_id": raw.get("runtime_session_id"),
            "instance_id": raw.get("instance_id"),
            "advisory": {
                "branch": raw.get("branch"),
                "worktree_path": raw.get("worktree_path"),
                "commit_sha": raw.get("commit_sha"),
                "pr_ref": raw.get("pr_ref"),
                "hostname": raw.get("hostname"),
                "pid": raw.get("pid"),
            },
        },
        "ownership_proof": {
            "type": "claim_id+claim_token",
            "claim_id": raw["id"],
            "claim_token_required": bool(raw["exclusive"]),
            "claim_token_present": bool(claim_token),
            "status": "verified-capable" if claim_token else "ambiguous-legacy-claim",
        },
    }
    if include_secret:
        claim["claim_token"] = claim_token
        claim["ownership_proof"]["claim_token"] = claim_token
    return claim


def _get_active_exclusive_claim_row(store: PgStore, work_item_id: int) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            SELECT * FROM claim
            WHERE repo_id = %s AND work_item_id = %s AND exclusive = true
              AND expires_at > now()
            ORDER BY created_at ASC
            LIMIT 1
            """,
            (store.repo_id, work_item_id),
        )
        row = cur.fetchone()
    return _norm(row) if row else None


def _get_active_coordinate_claim_row(store: PgStore, work_item_id: int) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            SELECT * FROM claim
            WHERE repo_id = %s AND work_item_id = %s AND exclusive = true
              AND claim_type = 'coordinate' AND expires_at > now()
            ORDER BY created_at ASC
            LIMIT 1
            """,
            (store.repo_id, work_item_id),
        )
        row = cur.fetchone()
    return _norm(row) if row else None


def _emit_claim_event(
    store: PgStore,
    claim_row: dict,
    *,
    event_type: str,
    actor: str,
    payload: dict,
) -> None:
    item = get_work_item(store, claim_row["work_item_id"])
    if item is None:
        return
    create_event(
        store,
        sprint_id=item["sprint_id"],
        actor=actor,
        event_type=event_type,
        source_type="system",
        work_item_id=item["id"],
        payload=payload,
    )


def _require_claim_proof(row: dict, claim_token: str | None) -> None:
    from .db import _require_claim_proof as _db_require_claim_proof
    _db_require_claim_proof(row, claim_token)


def _generate_claim_token() -> str:
    return secrets.token_urlsafe(24)


# ---------------------------------------------------------------------------
# Claim
# ---------------------------------------------------------------------------

def get_claim(store: PgStore, claim_id: int, *, include_secret: bool = False) -> dict | None:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM claim WHERE repo_id = %s AND id = %s",
            (store.repo_id, claim_id),
        )
        row = cur.fetchone()
    if row is None:
        return None
    return _serialize_claim(_norm(row), include_secret=include_secret)


def create_claim(
    store: PgStore,
    work_item_id: int,
    agent: str,
    claim_type: str = "execute",
    exclusive: bool = True,
    ttl_seconds: int = 300,
    branch: str | None = None,
    worktree_path: str | None = None,
    commit_sha: str | None = None,
    pr_ref: str | None = None,
    runtime_session_id: str | None = None,
    instance_id: str | None = None,
    hostname: str | None = None,
    pid: int | None = None,
    coordinate_claim_id: int | None = None,
    coordinate_claim_token: str | None = None,
) -> int:
    from .db import _require_claim_proof as _db_require_claim_proof
    if claim_type not in CLAIM_TYPES:
        raise ValueError(f"Invalid claim_type '{claim_type}'. Must be one of: {', '.join(CLAIM_TYPES)}")
    item = get_work_item(store, work_item_id)
    if item is None:
        raise ValueError(f"Work item #{work_item_id} not found")

    for attempt in range(MAX_CLAIM_TOKEN_INSERT_RETRIES):
        claim_token = _generate_claim_token()
        try:
            with store.conn.cursor() as cur:
                if exclusive:
                    conflict = _get_active_exclusive_claim_row(store, work_item_id)
                    if conflict:
                        if (
                            conflict["claim_type"] == "coordinate"
                            and coordinate_claim_id is not None
                            and coordinate_claim_id == conflict["id"]
                        ):
                            cur.execute(
                                "SELECT * FROM claim WHERE repo_id = %s AND id = %s",
                                (store.repo_id, coordinate_claim_id),
                            )
                            coord_row = cur.fetchone()
                            if coord_row is None:
                                raise ValueError(f"Coordinate claim #{coordinate_claim_id} not found")
                            _db_require_claim_proof(_norm(coord_row), coordinate_claim_token)
                        else:
                            raise ClaimConflict(
                                f"Item #{work_item_id} is exclusively claimed by '{conflict['agent']}' "
                                f"(claim #{conflict['id']})"
                            )
                cur.execute(
                    """
                    INSERT INTO claim
                        (repo_id, work_item_id, agent, claim_type, exclusive, expires_at,
                         branch, worktree_path, commit_sha, pr_ref,
                         claim_token, runtime_session_id, instance_id, hostname, pid)
                    VALUES (%s, %s, %s, %s, %s,
                            now() + (%s || ' seconds')::interval,
                            %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (store.repo_id, work_item_id, agent, claim_type, exclusive, ttl_seconds,
                     branch, worktree_path, commit_sha, pr_ref,
                     claim_token, runtime_session_id, instance_id, hostname, pid),
                )
                row = cur.fetchone()
            store.conn.commit()
            return row["id"]
        except ClaimConflict:
            raise
        except Exception as exc:
            store.conn.rollback()
            if _PSYCOPG_AVAILABLE and isinstance(exc, UniqueViolation) and "claim_token" in str(exc):
                if attempt == MAX_CLAIM_TOKEN_INSERT_RETRIES - 1:
                    raise RuntimeError("Failed to create claim: could not generate a unique token.") from exc
                continue
            raise
    raise RuntimeError("Unreachable")


def heartbeat_claim(
    store: PgStore,
    claim_id: int,
    claim_token: str | None,
    ttl_seconds: int = 300,
    actor: str | None = None,
    runtime_session_id: str | None = None,
    instance_id: str | None = None,
    branch: str | None = None,
    worktree_path: str | None = None,
    commit_sha: str | None = None,
    pr_ref: str | None = None,
    hostname: str | None = None,
    pid: int | None = None,
) -> None:
    from .db import _require_claim_proof as _db_require_claim_proof
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM claim WHERE repo_id = %s AND id = %s",
            (store.repo_id, claim_id),
        )
        row = cur.fetchone()
    if row is None:
        raise ValueError(f"Claim #{claim_id} not found")
    row = _norm(row)
    try:
        _db_require_claim_proof(row, claim_token)
    except ValueError as exc:
        event_type = "coordination-failure" if row["claim_token"] else "claim-ambiguity-detected"
        _emit_claim_event(
            store, row,
            event_type=event_type,
            actor=actor or "system",
            payload={
                "summary": f"Claim heartbeat rejected for claim #{claim_id}",
                "detail": str(exc),
                "tags": ["claims", "coordination", "heartbeat"],
                "operation": "heartbeat",
                "reason": "invalid-claim-proof" if row["claim_token"] else "legacy-ambiguous-claim",
                "claim": _claim_event_identity(row),
                "attempted_by": _claim_attempt_identity(
                    actor=actor, claim_id=claim_id, claim_token_present=claim_token is not None,
                    runtime_session_id=runtime_session_id, instance_id=instance_id,
                    branch=branch, worktree_path=worktree_path, commit_sha=commit_sha,
                    pr_ref=pr_ref, hostname=hostname, pid=pid,
                ),
            },
        )
        raise
    with store.conn.cursor() as cur:
        cur.execute(
            """
            UPDATE claim
            SET heartbeat = now(),
                expires_at = now() + (%s || ' seconds')::interval,
                runtime_session_id = COALESCE(%s, runtime_session_id),
                instance_id        = COALESCE(%s, instance_id),
                branch             = COALESCE(%s, branch),
                worktree_path      = COALESCE(%s, worktree_path),
                commit_sha         = COALESCE(%s, commit_sha),
                pr_ref             = COALESCE(%s, pr_ref),
                hostname           = COALESCE(%s, hostname),
                pid                = COALESCE(%s, pid)
            WHERE repo_id = %s AND id = %s
            """,
            (ttl_seconds, runtime_session_id, instance_id, branch, worktree_path,
             commit_sha, pr_ref, hostname, pid, store.repo_id, claim_id),
        )
    store.conn.commit()


def release_claim(store: PgStore, claim_id: int, claim_token: str | None, actor: str | None = None) -> None:
    from .db import _require_claim_proof as _db_require_claim_proof
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM claim WHERE repo_id = %s AND id = %s",
            (store.repo_id, claim_id),
        )
        row = cur.fetchone()
    if row is None:
        raise ValueError(f"Claim #{claim_id} not found")
    row = _norm(row)
    try:
        _db_require_claim_proof(row, claim_token)
    except ValueError as exc:
        _emit_claim_event(
            store, row,
            event_type="claim-ambiguity-detected" if not row["claim_token"] else "coordination-failure",
            actor=actor or "system",
            payload={
                "summary": f"Claim release rejected for claim #{claim_id}",
                "detail": str(exc),
                "tags": ["claims", "coordination", "release"],
                "operation": "release",
                "reason": "invalid-claim-proof" if row["claim_token"] else "legacy-ambiguous-claim",
                "claim": _claim_event_identity(row),
                "attempted_by": _claim_attempt_identity(
                    actor=actor, claim_id=claim_id, claim_token_present=claim_token is not None,
                ),
            },
        )
        raise
    with store.conn.cursor() as cur:
        cur.execute(
            "DELETE FROM claim WHERE repo_id = %s AND id = %s",
            (store.repo_id, claim_id),
        )
    store.conn.commit()


def handoff_claim(
    store: PgStore,
    claim_id: int,
    claim_token: str | None,
    *,
    actor: str,
    mode: str = "rotate",
    ttl_seconds: int = 300,
    runtime_session_id: str | None = None,
    instance_id: str | None = None,
    branch: str | None = None,
    worktree_path: str | None = None,
    commit_sha: str | None = None,
    pr_ref: str | None = None,
    hostname: str | None = None,
    pid: int | None = None,
    performed_by: str | None = None,
    note: str | None = None,
    allow_legacy_adopt: bool = False,
) -> dict:
    from .db import _require_claim_proof as _db_require_claim_proof
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM claim WHERE repo_id = %s AND id = %s",
            (store.repo_id, claim_id),
        )
        row = cur.fetchone()
    if row is None:
        raise ValueError(f"Claim #{claim_id} not found")
    if mode not in {"transfer", "rotate"}:
        raise ValueError("mode must be 'transfer' or 'rotate'")
    row = _norm(row)
    legacy_ambiguous = not bool(row["claim_token"])
    if legacy_ambiguous:
        if not allow_legacy_adopt:
            _emit_claim_event(
                store, row,
                event_type="claim-ambiguity-detected",
                actor=performed_by or actor,
                payload={
                    "summary": f"Legacy claim ambiguity detected for claim #{claim_id}",
                    "detail": "Handoff attempted for a legacy claim without a claim_token.",
                    "tags": ["claims", "coordination", "ambiguity", "legacy"],
                    "operation": "handoff",
                    "reason": "legacy-ambiguous-claim",
                    "claim": _claim_event_identity(row),
                    "attempted_by": _claim_attempt_identity(
                        actor=performed_by or actor, claim_id=claim_id,
                        claim_token_present=claim_token is not None,
                    ),
                },
            )
            raise ValueError(
                f"Claim #{claim_id} is a legacy ambiguous claim with no claim_token. "
                "Use allow_legacy_adopt to mint a new ownership proof."
            )
        mode = "rotate"
    else:
        try:
            _db_require_claim_proof(row, claim_token)
        except ValueError as exc:
            _emit_claim_event(
                store, row,
                event_type="coordination-failure",
                actor=performed_by or actor,
                payload={
                    "summary": f"Claim handoff rejected for claim #{claim_id}",
                    "detail": str(exc),
                    "tags": ["claims", "coordination", "handoff"],
                    "operation": "handoff",
                    "reason": "invalid-claim-proof",
                    "claim": _claim_event_identity(row),
                    "attempted_by": _claim_attempt_identity(
                        actor=performed_by or actor, claim_id=claim_id,
                        claim_token_present=claim_token is not None,
                    ),
                },
            )
            raise

    from_identity = _claim_event_identity(row)
    next_claim_token = row["claim_token"]
    if mode == "rotate" or not next_claim_token:
        next_claim_token = _generate_claim_token()

    with store.conn.cursor() as cur:
        cur.execute(
            """
            UPDATE claim
            SET agent = %s, claim_token = %s,
                expires_at = now() + (%s || ' seconds')::interval,
                runtime_session_id = %s, instance_id = %s, branch = %s,
                worktree_path = %s, commit_sha = %s, pr_ref = %s,
                hostname = %s, pid = %s, heartbeat = now()
            WHERE repo_id = %s AND id = %s
            """,
            (actor, next_claim_token, ttl_seconds,
             runtime_session_id, instance_id, branch, worktree_path, commit_sha, pr_ref,
             hostname, pid, store.repo_id, claim_id),
        )
    store.conn.commit()

    updated = get_claim(store, claim_id, include_secret=True)
    assert updated is not None
    event_type = "claim-ownership-corrected" if legacy_ambiguous else "claim-handoff"
    _emit_claim_event(
        store, updated,
        event_type=event_type,
        actor=performed_by or actor,
        payload={
            "summary": (
                f"Claim #{claim_id} ownership corrected"
                if legacy_ambiguous
                else f"Claim #{claim_id} handed off to {actor}"
            ),
            "detail": note or (
                "A legacy ambiguous claim was adopted and re-issued."
                if legacy_ambiguous
                else f"Claim ownership transferred with mode={mode}."
            ),
            "tags": ["claims", "handoff", "coordination"],
            "operation": "handoff",
            "mode": mode,
            "legacy_adopted": legacy_ambiguous,
            "token_rotated": mode == "rotate" or legacy_ambiguous,
            "from_identity": from_identity,
            "to_identity": _claim_event_identity(updated),
        },
    )
    return updated


def list_claims_by_sprint(
    store: PgStore,
    sprint_id: int,
    active_only: bool = True,
    expiring_within_seconds: int | None = None,
) -> list[dict]:
    query = """
        SELECT c.*, wi.title AS item_title, wi.status AS item_status
        FROM claim c
        JOIN work_item wi ON c.repo_id = wi.repo_id AND c.work_item_id = wi.id
        WHERE c.repo_id = %s AND wi.sprint_id = %s
    """
    params: list = [store.repo_id, sprint_id]
    if active_only:
        query += " AND c.expires_at > now()"
    if expiring_within_seconds is not None:
        query += " AND c.expires_at <= now() + (%s || ' seconds')::interval"
        params.append(expiring_within_seconds)
    query += " ORDER BY c.expires_at ASC"
    with store.conn.cursor() as cur:
        cur.execute(query, params)
        rows = cur.fetchall()
    return [_serialize_claim(_norm(r)) for r in rows]


def list_claims(store: PgStore, work_item_id: int, active_only: bool = True) -> list[dict]:
    if active_only:
        with store.conn.cursor() as cur:
            cur.execute(
                """
                SELECT * FROM claim
                WHERE repo_id = %s AND work_item_id = %s AND expires_at > now()
                ORDER BY created_at ASC
                """,
                (store.repo_id, work_item_id),
            )
            rows = cur.fetchall()
    else:
        with store.conn.cursor() as cur:
            cur.execute(
                "SELECT * FROM claim WHERE repo_id = %s AND work_item_id = %s ORDER BY created_at ASC",
                (store.repo_id, work_item_id),
            )
            rows = cur.fetchall()
    return [_serialize_claim(_norm(r)) for r in rows]


def find_claim_by_identity(
    store: PgStore,
    *,
    instance_id: str | None = None,
    hostname: str | None = None,
    pid: int | None = None,
    runtime_session_id: str | None = None,
    active_only: bool = True,
) -> list[dict]:
    if not any([instance_id, runtime_session_id, (hostname and pid is not None)]):
        raise ValueError(
            "At least one of --instance-id, --runtime-session-id, or "
            "--hostname + --pid must be provided to resume a claim."
        )
    conditions: list[str] = ["repo_id = %s"]
    params: list = [store.repo_id]
    if active_only:
        conditions.append("expires_at > now()")
    if instance_id:
        conditions.append("instance_id = %s")
        params.append(instance_id)
    if runtime_session_id:
        conditions.append("runtime_session_id = %s")
        params.append(runtime_session_id)
    if hostname and pid is not None:
        conditions.append("(hostname = %s AND pid = %s)")
        params.extend([hostname, pid])
    where = " AND ".join(conditions)
    with store.conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM claim WHERE {where} ORDER BY created_at DESC",
            params,
        )
        rows = cur.fetchall()
    return [_serialize_claim(_norm(r)) for r in rows]


# ---------------------------------------------------------------------------
# Ref
# ---------------------------------------------------------------------------

def add_ref(store: PgStore, work_item_id: int, ref_type: str, url: str, label: str = "") -> int:
    if ref_type not in REF_TYPES:
        raise ValueError(f"Invalid ref_type '{ref_type}'. Must be one of: {', '.join(REF_TYPES)}")
    _validate_ref_url(url)
    item = get_work_item(store, work_item_id)
    if item is None:
        raise ValueError(f"Work item #{work_item_id} not found")
    with store.conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO ref (repo_id, work_item_id, ref_type, url, label)
            VALUES (%s, %s, %s, %s, %s)
            RETURNING id
            """,
            (store.repo_id, work_item_id, ref_type, url, label),
        )
        row = cur.fetchone()
    store.conn.commit()
    return row["id"]


def list_refs(store: PgStore, work_item_id: int) -> list[dict]:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM ref WHERE repo_id = %s AND work_item_id = %s ORDER BY created_at ASC",
            (store.repo_id, work_item_id),
        )
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def remove_ref(store: PgStore, ref_id: int, work_item_id: int) -> None:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT id FROM ref WHERE repo_id = %s AND id = %s AND work_item_id = %s",
            (store.repo_id, ref_id, work_item_id),
        )
        row = cur.fetchone()
    if row is None:
        raise ValueError(f"Ref #{ref_id} not found on item #{work_item_id}")
    with store.conn.cursor() as cur:
        cur.execute(
            "DELETE FROM ref WHERE repo_id = %s AND id = %s",
            (store.repo_id, ref_id),
        )
    store.conn.commit()


# ---------------------------------------------------------------------------
# Dep
# ---------------------------------------------------------------------------

def add_dep(store: PgStore, item_id: int, blocked_item_id: int) -> int:
    if item_id == blocked_item_id:
        raise ValueError("An item cannot depend on itself")
    if get_work_item(store, item_id) is None:
        raise ValueError(f"Work item #{item_id} not found")
    if get_work_item(store, blocked_item_id) is None:
        raise ValueError(f"Work item #{blocked_item_id} not found")
    with store.conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO dep (repo_id, item_id, blocked_item_id)
            VALUES (%s, %s, %s)
            ON CONFLICT (repo_id, item_id, blocked_item_id) DO NOTHING
            """,
            (store.repo_id, item_id, blocked_item_id),
        )
        cur.execute(
            "SELECT id FROM dep WHERE repo_id = %s AND item_id = %s AND blocked_item_id = %s",
            (store.repo_id, item_id, blocked_item_id),
        )
        row = cur.fetchone()
    store.conn.commit()
    return row["id"]


def list_deps_blocking(store: PgStore, item_id: int) -> list[dict]:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            SELECT d.id, d.item_id, d.blocked_item_id, d.created_at,
                   wi.title AS blocker_title, wi.status AS blocker_status
            FROM dep d
            JOIN work_item wi ON d.repo_id = wi.repo_id AND d.item_id = wi.id
            WHERE d.repo_id = %s AND d.blocked_item_id = %s
            ORDER BY d.created_at ASC
            """,
            (store.repo_id, item_id),
        )
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def list_deps_blocked_by(store: PgStore, item_id: int) -> list[dict]:
    with store.conn.cursor() as cur:
        cur.execute(
            """
            SELECT d.id, d.item_id, d.blocked_item_id, d.created_at,
                   wi.title AS waiting_title, wi.status AS waiting_status
            FROM dep d
            JOIN work_item wi ON d.repo_id = wi.repo_id AND d.blocked_item_id = wi.id
            WHERE d.repo_id = %s AND d.item_id = %s
            ORDER BY d.created_at ASC
            """,
            (store.repo_id, item_id),
        )
        rows = cur.fetchall()
    return [_norm(r) for r in rows]


def remove_dep(store: PgStore, dep_id: int, item_id: int) -> None:
    with store.conn.cursor() as cur:
        cur.execute(
            "SELECT id FROM dep WHERE repo_id = %s AND id = %s AND (item_id = %s OR blocked_item_id = %s)",
            (store.repo_id, dep_id, item_id, item_id),
        )
        row = cur.fetchone()
    if row is None:
        raise ValueError(f"Dep #{dep_id} not found for item #{item_id}")
    with store.conn.cursor() as cur:
        cur.execute("DELETE FROM dep WHERE repo_id = %s AND id = %s", (store.repo_id, dep_id))
    store.conn.commit()


def get_ready_items(store: PgStore, sprint_id: int) -> list[dict]:
    items = list_work_items(store, sprint_id=sprint_id, status="pending")
    ready = []
    for item in items:
        blockers = list_deps_blocking(store, item["id"])
        unresolved = [b for b in blockers if b["blocker_status"] != "done"]
        if not unresolved:
            ready.append({**item, "blockers_resolved": len(blockers), "unresolved_blockers": 0})
    return ready


# ---------------------------------------------------------------------------
# Backlog seeding
# ---------------------------------------------------------------------------

def backlog_seed_from_candidates(
    store: PgStore,
    source_sprint_id: int,
    target_sprint_id: int,
    actor: str = "system",
) -> list[dict]:
    import json as _json
    if get_sprint(store, source_sprint_id) is None:
        raise ValueError(f"Source sprint #{source_sprint_id} not found")
    if get_sprint(store, target_sprint_id) is None:
        raise ValueError(f"Target sprint #{target_sprint_id} not found")

    candidates = list_knowledge_candidates(store, source_sprint_id)
    if not candidates:
        return []

    existing_events = list_events(store, target_sprint_id)
    already_seeded: set[int] = set()
    for ev in existing_events:
        if ev["event_type"] == "backlog-seeded":
            p = _json.loads(ev.get("payload") or "{}") if isinstance(ev.get("payload"), str) else (ev.get("payload") or {})
            if "source_event_id" in p:
                already_seeded.add(p["source_event_id"])

    track_id = get_or_create_track(store, target_sprint_id, "knowledge")
    seeded = []
    for candidate in candidates:
        if candidate["id"] in already_seeded:
            continue
        summary = candidate["payload"].get("summary", f"Knowledge item from event #{candidate['id']}")
        title = f"[knowledge] {summary}"
        item_id = create_work_item(store, target_sprint_id, track_id, title)
        create_event(
            store, target_sprint_id,
            actor=actor,
            event_type="backlog-seeded",
            source_type="system",
            work_item_id=item_id,
            payload={
                "source_sprint_id": source_sprint_id,
                "source_item_id": candidate.get("work_item_id"),
                "source_event_id": candidate["id"],
                "source_event_type": candidate["event_type"],
            },
        )
        seeded.append(get_work_item(store, item_id))
    return seeded


# ---------------------------------------------------------------------------
# Maintain helpers
# ---------------------------------------------------------------------------

def purge_expired_claims(store: PgStore, sprint_id: int) -> int:
    """Delete all expired claims for items in the given sprint. Returns count deleted."""
    with store.conn.cursor() as cur:
        cur.execute(
            """
            DELETE FROM claim
            WHERE repo_id = %s
              AND work_item_id IN (
                SELECT id FROM work_item WHERE repo_id = %s AND sprint_id = %s
              )
              AND expires_at <= now()
            """,
            (store.repo_id, store.repo_id, sprint_id),
        )
        count = cur.rowcount
    store.conn.commit()
    return count


# ---------------------------------------------------------------------------
# NDJSON export / import (for migrate-to-remote)
# ---------------------------------------------------------------------------

_EXPORT_TABLES = ("sprint", "track", "work_item", "event", "claim", "ref", "dep")


def export_ndjson(sqlite_conn: Any, repo_id: str, out: Any) -> dict[str, int]:
    """Export all rows for repo_id from a sqlite connection as NDJSON to file-like out.

    Returns row counts per table.
    """
    import sqlite3 as _sqlite3

    counts: dict[str, int] = {}

    def _row_to_dict(row: _sqlite3.Row) -> dict:
        return dict(row)

    def _sqlite_events(conn: Any, rid: str) -> list[dict]:
        rows = conn.execute("SELECT * FROM event WHERE 1=1 ORDER BY id ASC").fetchall()
        result = []
        for r in rows:
            d = _row_to_dict(r)
            payload_raw = d.get("payload") or "{}"
            try:
                d["payload"] = json.loads(payload_raw) if isinstance(payload_raw, str) else payload_raw
            except json.JSONDecodeError:
                d["payload"] = {}
            result.append(d)
        return result

    table_queries = {
        "sprint": "SELECT * FROM sprint ORDER BY id ASC",
        "track": "SELECT * FROM track ORDER BY id ASC",
        "work_item": "SELECT * FROM work_item ORDER BY id ASC",
        "claim": "SELECT * FROM claim ORDER BY id ASC",
        "ref": "SELECT * FROM ref ORDER BY id ASC",
        "dep": "SELECT * FROM dep ORDER BY id ASC",
    }

    for table in _EXPORT_TABLES:
        if table == "event":
            rows = _sqlite_events(sqlite_conn, repo_id)
        else:
            raw = sqlite_conn.execute(table_queries[table]).fetchall()
            rows = [_row_to_dict(r) for r in raw]
        for row in rows:
            record = {"table": table, "repo_id": repo_id, "data": row}
            out.write(json.dumps(record) + "\n")
        counts[table] = len(rows)

    return counts


def import_ndjson(store: PgStore, records: list[dict], *, replace: bool = False) -> dict[str, int]:
    """Import NDJSON records into pg, preserving original sqlite integer IDs.

    If replace=True, deletes existing rows for store.repo_id first.
    All work done in a single transaction.
    """
    counts: dict[str, int] = {t: 0 for t in _EXPORT_TABLES}

    with store.conn.cursor() as cur:
        if replace:
            for table in reversed(_EXPORT_TABLES):
                cur.execute(f"DELETE FROM {table} WHERE repo_id = %s", (store.repo_id,))

        for record in records:
            table = record["table"]
            data = record["data"]
            rid = record.get("repo_id", store.repo_id)
            _import_row(cur, table, rid, data)
            counts[table] = counts.get(table, 0) + 1

        # Advance sequences so next auto-generated IDs don't collide.
        for table in _EXPORT_TABLES:
            try:
                cur.execute(
                    f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                    f"COALESCE((SELECT MAX(id) FROM {table} WHERE repo_id = %s), 0) + 1, false)",
                    (store.repo_id,),
                )
            except Exception:
                pass

    store.conn.commit()
    return counts


def _import_row(cur: Any, table: str, repo_id: str, data: dict) -> None:
    """Insert one row into the named table, using OVERRIDING SYSTEM VALUE for identity columns."""
    row = dict(data)
    row["repo_id"] = repo_id

    # Canonicalise event payloads during import.
    if table == "event":
        payload = row.get("payload") or {}
        if isinstance(payload, str):
            payload = json.loads(payload)
        event_type = row.get("event_type", "")
        row["payload"] = json.dumps(_contracts.canonicalize_event_payload(event_type, payload))

    cols = list(row.keys())
    placeholders = ", ".join(["%s"] * len(cols))
    col_names = ", ".join(cols)
    values = [row[c] for c in cols]

    cur.execute(
        f"INSERT INTO {table} ({col_names}) OVERRIDING SYSTEM VALUE VALUES ({placeholders})",
        values,
    )
